-- ============================================================
-- V1: BECS BPY File Processing Schema  (H2-compatible)
-- H2 uses BIGINT GENERATED BY DEFAULT AS IDENTITY instead of
-- BIGSERIAL (which is PostgreSQL-specific).
-- ============================================================

-- Master record of every BPY or RET bundle file received
CREATE TABLE becs_file (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name           VARCHAR(512)    NOT NULL,
    file_path           VARCHAR(1024)   NOT NULL,
    received_at         TIMESTAMP       NOT NULL DEFAULT NOW(),
    processed_at        TIMESTAMP,
    archived_path       VARCHAR(1024),

    -- 'BPY', 'RET' or 'NDE' — which kind of input file this row represents
    file_type           VARCHAR(10)     NOT NULL,

    -- Debulked output produced from a .bpy.nnn input file
    bpy_out_file_name   VARCHAR(512),
    bpy_output_file_path VARCHAR(1024),
    bpy_record_count    INTEGER,

    -- Debulked output produced from a .ret.nnn input file
    ret_out_file_name   VARCHAR(512),
    ret_output_file_path VARCHAR(1024),
    ret_record_count    INTEGER,

    -- Debulked output produced from a .nde.nnn input file
    nde_out_file_name   VARCHAR(512),
    nde_output_file_path VARCHAR(1024),
    nde_record_count    INTEGER,

    status              VARCHAR(50)     NOT NULL DEFAULT 'RECEIVED',
    error_message       CLOB,
    record_count        INTEGER,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_becs_file_status      ON becs_file(status);
CREATE INDEX idx_becs_file_received_at ON becs_file(received_at);
CREATE INDEX idx_becs_file_type        ON becs_file(file_type);

-- File header (one per reel in the source file)
CREATE TABLE becs_file_header (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    becs_file_id          BIGINT      NOT NULL REFERENCES becs_file(id),
    reel_sequence_number VARCHAR(2),
    financial_institution VARCHAR(3),
    user_preferred_spec  VARCHAR(26),
    user_id              VARCHAR(6),
    description          VARCHAR(12),
    processing_date      DATE,
    created_at           TIMESTAMP   NOT NULL DEFAULT NOW()
);

-- File trailer (one per reel in the source file)
CREATE TABLE becs_file_trailer (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    becs_file_id         BIGINT      NOT NULL REFERENCES becs_file(id),
    bsb_filler          VARCHAR(7),
    net_total_amount    BIGINT,
    credit_total_amount BIGINT,
    debit_total_amount  BIGINT,
    record_count        INTEGER,
    created_at          TIMESTAMP   NOT NULL DEFAULT NOW()
);

-- Individual payment/transaction records debulked from a BECS file.
-- header_id / trailer_id link each record to the reel it sat under.
CREATE TABLE becs_payment_record (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    becs_file_id         BIGINT          NOT NULL REFERENCES becs_file(id),
    header_id           BIGINT          REFERENCES becs_file_header(id),
    trailer_id          BIGINT          REFERENCES becs_file_trailer(id),
    bsb_number          VARCHAR(7),
    account_number      VARCHAR(9),
    indicator           CHAR(1),
    transaction_code    VARCHAR(2),
    amount_cents        BIGINT,
    account_name        VARCHAR(32),
    lodgement_reference VARCHAR(18),
    trace_bsb           VARCHAR(7),
    trace_account       VARCHAR(9),
    remitter_name       VARCHAR(16),
    withholding_tax     BIGINT,
    line_number         INTEGER,
    record_type         CHAR(1),
    output_file_path    VARCHAR(1024),
    status              VARCHAR(50)     NOT NULL DEFAULT 'PENDING',
    -- Fraud-check response from the external PRM web service (future
    -- integration): 'A', 'D', 'N', 'T', or empty/null when not yet recorded
    prm_status          CHAR(1),
    error_message       CLOB,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_payment_becs_file_id ON becs_payment_record(becs_file_id);
CREATE INDEX idx_payment_header_id   ON becs_payment_record(header_id);
CREATE INDEX idx_payment_trailer_id  ON becs_payment_record(trailer_id);
CREATE INDEX idx_payment_txn_code    ON becs_payment_record(transaction_code);
CREATE INDEX idx_payment_bsb         ON becs_payment_record(bsb_number);
CREATE INDEX idx_payment_status      ON becs_payment_record(status);

-- Per-BSB, per-output-type debulked-output sequence counter (001-999, wraps
-- back to 001). sequence_key is "{bsb_number}:{BPY|RET|NDE}" so each output
-- type for the same BSB number counts independently.
CREATE TABLE becs_bsb_sequence (
    sequence_key  VARCHAR(40) PRIMARY KEY,
    last_sequence INTEGER     NOT NULL
);

-- Processing audit log
CREATE TABLE becs_processing_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    becs_file_id BIGINT      REFERENCES becs_file(id),
    level       VARCHAR(10) NOT NULL,
    message     CLOB        NOT NULL,
    logged_at   TIMESTAMP   NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_proc_log_file_id ON becs_processing_log(becs_file_id);
